apiVersion: v1
kind: Namespace
metadata:
  name: school

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: school
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: school
spec:
  commonName: school.example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: school-ingress
  namespace: school
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts: 
    - school.example.com
    secretName: selfsigned-cert-tls
  rules:
  - host: school.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: school-svc
          servicePort: 80
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: school
  namespace: school
spec:
  replicas: 2
  selector:
    matchLabels:
      app: school
  template:
    metadata:
      labels:
        app: school
    spec:
      containers:
      - name: school
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: school-svc
  namespace: school
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: school
